version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mobifi_frontend
    ports:
      - '5000:5000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mobifi_backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - sail
  db:
    image: postgres
    container_name: mobifi_db
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mobifi_ticketing
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
    networks:
      - sail
  pgadmin:
    image: dpage/pgadmin4
    container_name: mobifi_pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: hanieasemi76@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - sail
    logging:
      driver: none

networks:
  sail:
    driver: bridge
